### ISSUE TITLE
0.14.0 Release has inconsistent terraform requirements

### ISSUE THREAD

**Issue by robert-r-meyer** [clouddrove/terraform-aws-sftp#13]
[0.14.0 ](https://github.com/clouddrove/terraform-aws-sftp/releases/tag/0.14.0) introduced the use of `sensitive` in accordance with Terraform 0.14.0. 

https://github.com/clouddrove/terraform-aws-sftp/commit/52be35d0167621906f7c9cd798771e6deb733f73#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288e

This change is a breaking change as the[ versions ](https://github.com/clouddrove/terraform-aws-sftp/blob/0.14.0/versions.tf) allows for `>= 0.12.0` 

Any attempt to run with TF < 0.14.0 causes errors:

![image](https://user-images.githubusercontent.com/20780405/134951338-0c681a20-d5d7-4f04-9fbc-278416e40562.png)

**Comment by omsharma07** [comment]
Please use tags according to your terraform version.
https://github.com/clouddrove/terraform-aws-sftp/tags

And keep us posted if you face any issues. Thanks!
