### ISSUE TITLE
A policy called sftp-s3-transfer already exists. Duplicate names are not allowed.

### ISSUE THREAD

**Issue by evgenyidf** [clouddrove/terraform-aws-sftp#39]
There are few issues with duplication and incorrect settings:

1. main.tf line 152 / 161
   Logging policy & role names should not use pure ID, but like following: 
   `name   = "${module.labels.id}_logging"`
   
2. Since you use now map instead of list, 'aws_transfer_ssh_key' on line 242 should be defined like following:
    ```
    resource "aws_transfer_ssh_key" "transfer_server_ssh_key" {
          for_each  = var.enabled ? var.sftp_users : {}
          server_id = join("", aws_transfer_server.transfer_server[*].id)
          user_name = var.sftp_users[each.key].user_name
          body      = var.sftp_users[each.key].public_key
        }
```

**Comment by theprashantyadav** [comment]
Hello @evgenyidf 
I really liked that you mentioned these changes.
We have fixed all this and used the format function in the name. You can check in the PR given below
PR:- https://github.com/clouddrove/terraform-aws-sftp/pull/40/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbb
